const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const {JSDOM}=require('jsdom');
const flush=()=>new Promise(resolve=>setImmediate(resolve));
const source=fs.readFileSync('frontend/static/script/js/modules/js/kot_v2.js','utf8');
function setup(){
 const dom=new JSDOM('<div id="v-pills-dashboard"></div><div id="kot" class="page_loader"></div>',{url:'http://localhost/#/kot_v2',runScripts:'outside-only'}),w=dom.window;
 w.$=require('jquery')(w);w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;this.dispatchEvent(new w.Event('close'));};
 const calls=[],effects=[],errors=[];
 const sale={_id:'a'.repeat(24),table_number:'6',dine_type:'Dine-in',person_count:2,updated_date:'2026-10-05T06:00:00Z',created_date:'2026-10-05T06:00:00Z',payment_status:'Unpaid',sale_process:'KOT',sales_total:60,items:[{item_id:'tea',line_id:'original',item_name:'Tea',item_quantity:2,item_price:30}],restaurant_details:{rounds:[{id:'c0',items:[{id:'c0i0',line_key:'original',product:'tea',name:'Tea',quantity:2,served:0,remaining:2}]}]}};
 let search;
 w.PosnicPro={i18n:{t:(_,fallback)=>fallback},local:{get:k=>({table_options:'enable',branch_id_set:'b',username:'owner',currencySign:'₹'}[k])},escapeHtml:s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),HideSideBarModal(){},alert:(_,m)=>errors.push(m),restaurantFeedback:{apply(){},load(){},play:k=>effects.push(k)},kot:{bindProductSearch:(_,callback)=>search=callback,editLine:(l,q)=>({product_id:l.item_id,line_id:l.line_id,quantity:q??l.item_quantity,price:l.item_price}),},kotWorkspace:{editPayload:(s,items)=>({order_id:s._id,items,seen_at:s.updated_date})}};
 for(const method of ['get','post','put'])w.PosnicPro[method]=(o,done,fail)=>{const body=typeof o.data==='string'?JSON.parse(o.data):o.data;calls.push({method,url:o.url,body});if(setup.failure&&method==='post'){fail({responseJSON:{message:'Offline'}});return;}let data={};if(o.url==='captain/v1/tables')data={tables:[{id:'t6',tableorder_value:'6',status:'occupied',orders:[{id:sale._id}]},{id:'t7',tableorder_value:'7',status:'available',orders:[]}]};else if(o.url==='sales')data={list:sale.payment_status==='Paid'?[]:[sale],total:1};else if(o.url==='sales/'+sale._id)data=JSON.parse(JSON.stringify(sale));else if(o.url==='items/instantItemTax')data={id:'tax',rate:5,name:'GST'};else if(o.url==='items/instanceItemInsert')data={id:'instant',selling_price:25};done({type:'success',data});};
 w.eval(source);const app=w.PosnicPro.kot_v2;
 const click=async a=>{w.document.querySelector('[data-action="'+a+'"]').click();await flush();};
 return {dom,w,app,calls,effects,errors,sale,click,search:()=>search,close:()=>dom.window.close()};
}
test('add again stays in a durable draft, preserves original quantity, sends one additional line',async()=>{const h=setup();h.app.state.selected=h.sale._id;h.app.showDataTablePage();await flush();h.app.state.selected=h.sale._id;await h.app.refresh();await h.click('again');h.w.document.querySelector('dialog form').dispatchEvent(new h.w.Event('submit',{cancelable:true}));await flush();assert.equal(h.calls.filter(c=>c.method==='post').length,0);assert.equal(h.sale.items[0].item_quantity,2);assert.equal(h.app.state.draft.items[0].quantity,1);assert.notEqual(h.app.state.draft.items[0].line_id,'original');assert.ok(h.w.localStorage.length);await h.click('send');const sent=h.calls.find(c=>c.url==='sales/updateOrder');assert.equal(sent.body.items.length,2);assert.equal(sent.body.items[0].quantity,2);assert.equal(sent.body.items[1].quantity,1);assert.deepEqual(h.effects,['first','sent']);assert.equal(h.app.state.draft,null);h.close();});
test('off-menu creation does not submit a kitchen ticket',async()=>{const h=setup();h.app.showDataTablePage();await flush();h.app.state.selected=h.sale._id;await h.app.refresh();await h.click('offmenu');h.w.document.querySelector('[name=name]').value='Soup';h.w.document.querySelector('[name=price]').value='25';h.w.document.querySelector('dialog form').dispatchEvent(new h.w.Event('submit',{cancelable:true}));await flush();assert.equal(h.app.state.draft.items[0].name,'Soup');assert.equal(h.calls.filter(c=>c.url==='sales/updateOrder'||c.url==='sales/qrOrder').length,0);const payload=h.calls.find(c=>c.url==='items/instanceItemInsert').body;assert.equal(payload.quick_sale_default_tax,true);assert.equal(payload.quick_sale_tax.rate,5);h.close();});
test('failed send retains immutable request and has no success animation',async()=>{const h=setup();h.app.showDataTablePage();await flush();h.app.state.selected=h.sale._id;await h.app.refresh();await h.click('add');h.search()({item_id:'new',selling_price:10,item_name:'Naan'},1,()=>{});setup.failure=true;await h.click('send');const saved=JSON.stringify(h.app.state.draft.intent);await h.click('send');assert.equal(JSON.stringify(h.app.state.draft.intent),saved);assert.equal(h.effects.includes('sent'),false);assert.equal(h.errors.length,2);setup.failure=false;h.close();});
test('serving a portion targets the exact round without opening confirmation',async()=>{const h=setup();h.app.showDataTablePage();await flush();h.app.state.selected=h.sale._id;await h.app.refresh();await h.click('serve');assert.equal(h.w.document.querySelector('dialog'),null);assert.deepEqual(h.calls.find(c=>c.url==='sales/serveKitchenItems').body.items,[{id:'c0i0',quantity:1}]);h.close();});
test('settled order is cleared after refresh and active filter is first',async()=>{const h=setup();h.app.showDataTablePage();await flush();h.app.state.selected=h.sale._id;await h.app.refresh();h.sale.payment_status='Paid';await h.app.refresh();assert.equal(h.app.state.selected,null);assert.equal(h.app.state.sale,null);assert.equal(h.w.document.querySelector('.kv2-floor nav button').textContent,'Active');h.close();});
test('floor query includes partial payments until fully settled',async()=>{const h=setup();h.sale.payment_status='Pending';h.app.showDataTablePage();await flush();const filters=JSON.parse(h.calls.find(c=>c.url==='sales').body.filters);assert.deepEqual(filters.payment_status,{$nin:['Paid','Cancelled']});assert.equal(h.app.state.sales.length,1);h.close();});
test('customer changes during an additional round persist on its saved order',async()=>{const h=setup();h.w.$.fn.autocomplete=function(){return this;};h.app.showDataTablePage();await flush();h.app.state.selected=h.sale._id;await h.app.refresh();await h.click('add');await h.click('customer');h.w.document.querySelector('[name=name]').value='Guest';h.w.document.querySelector('[name=phone]').value='9876543210';h.w.document.querySelector('dialog form').dispatchEvent(new h.w.Event('submit',{cancelable:true}));await flush();const saved=h.calls.find(c=>c.url==='sales/orderCustomer');assert.equal(saved.body.saleId,h.sale._id);assert.equal(saved.body.name,'Guest');assert.equal(h.app.state.draft.customer.name,'Guest');assert.equal(h.calls.some(c=>c.url==='sales/updateOrder'),false);h.close();});
test('empty orders offer a table picker with distinct available and occupied choices',async()=>{const h=setup();h.sale.payment_status='Paid';h.app.showDataTablePage();await flush();assert.match(h.w.document.querySelector('.kv2-welcome').textContent,/No active orders/);await h.click('new');const d=h.w.document.querySelector('.kv2-seating-dialog');assert.equal(d.querySelector('[name=table]').value,'t7');assert.equal(d.querySelector('[value=t6]').disabled,true);d.querySelector('[data-guests="6"]').click();assert.equal(d.querySelector('[name=guests]').value,'6');assert.equal(d.querySelector('[data-guests="6"]').getAttribute('aria-pressed'),'true');const input=d.querySelector('[name=guests]');input.value='3';input.dispatchEvent(new h.w.Event('input'));assert.equal(d.querySelector('[data-guests="3"]').getAttribute('aria-pressed'),'true');assert.equal(d.querySelector('[data-guests="6"]').getAttribute('aria-pressed'),'false');assert.equal(h.calls.filter(c=>c.method==='post').length,0);h.close();});
