// Auto-generated file - DO NOT EDIT
// This file is automatically generated by the generate-routes script

const express = require('express');
const router = express.Router();

// Import all route files
const activityLogRoutes = require('./activity-logs.routes');
const authRoutes = require('./auth.routes');
const authUtilsRoutes = require('./auth-utils.routes');
const baseRoutes = require('./base.routes');
const branchesRoutes = require('./branches.routes');
const categoriesRoutes = require('./categories.routes');
const customerCategoryRoutes = require('./customer-categories.routes');
const commonPdfRoutes = require('./common-pdf.routes');
const customersRoutes = require('./customers.routes');
const dashboardRoutes = require('./dashboard.routes');
const easyTableRoutes = require('./easy-tables.routes');
const expensesRoutes = require('./expenses.routes');
const installRoutes = require('./install.routes');
const itemsRoutes = require('./items.routes');
const receivingsRoutes = require('./receivings.routes');
const registersRoutes = require('./registers.routes');
const salesRoutes = require('./sales.routes');
const settingsRoutes = require('./settings.routes'); // Note: File not renamed, but route will be /settings
const stockLogsRoutes = require('./stock-logs.routes');
const suppliersRoutes = require('./suppliers.routes');
const usersRoutes = require('./users.routes'); // Updated from userRoutes
const variantsRoutes = require('./variants.routes');
const whatsappRoutes = require('./whatsapp.routes');

// Root endpoint for /api
router.get('/', (req, res) => {
  res.status(200).json({
    type: 'success',
    message: 'Posnic API v2',
    data: null,
  });
});

/*
 * The access grid, enforced - for API keys only.
 *
 * Each route file protects itself, so req.user is already set by the time a
 * handler runs; this sits in front of all of them and refuses anything the
 * key's own grid does not permit. It does nothing at all for a session, whose
 * requests never set req.isApiKey: turning enforcement on for the tills in the
 * same change would risk locking a shop out of its own counter over a route
 * mapped wrongly, which deserves its own testing rather than a free ride on
 * this one.
 */
const { enforceApiKeyAcl } = require('../middleware/api-key');
router.use(enforceApiKeyAcl);

// Mount routes with consistent naming
router.use('/activity-logs', activityLogRoutes);
router.use('/auth', authRoutes);
router.use('/auth-utils', authUtilsRoutes);
router.use('/base', baseRoutes);
router.use('/branches', branchesRoutes);
router.use('/categories', categoriesRoutes);
router.use('/customer-category', customerCategoryRoutes);
router.use('/customercategory', customerCategoryRoutes); // Legacy PHP path support
router.use('/common-pdf', commonPdfRoutes);
router.use('/customers', customersRoutes);
router.use('/dashboard', dashboardRoutes); // Removed /api prefix for consistency
router.use('/easy-table', easyTableRoutes);
router.use('/expenses', expensesRoutes);
router.use('/install', installRoutes);
router.use('/items', itemsRoutes);
router.use('/receivings', receivingsRoutes);
router.use('/registers', registersRoutes);
router.use('/sales', salesRoutes);
router.use('/settings', settingsRoutes); // Primary path
router.use('/setting', settingsRoutes); // Legacy PHP path support
router.use('/stock-logs', stockLogsRoutes); // Changed from stocklogs to stock-logs
router.use('/stocklogs', stockLogsRoutes); // Legacy path support
router.use('/suppliers', suppliersRoutes);
router.use('/users', usersRoutes);
router.use('/variants', variantsRoutes);
router.use('/whatsapp', whatsappRoutes);

module.exports = router;
