'use strict';

const {
  HTTP_STATUS,
  ERROR_MESSAGES,
  SUCCESS_MESSAGES,
  VALIDATION_RULES,
  COLLECTIONS,
  DEFAULTS,
  FILE_PATHS,
} = require('../../../src/constants/settings.constants');

describe('settings.constants', () => {
  test('exports status, defaults, and paths', () => {
    expect(HTTP_STATUS).toEqual({
      OK: 200,
      BAD_REQUEST: 400,
      UNAUTHORIZED: 401,
      NOT_FOUND: 404,
      INTERNAL_ERROR: 500,
    });

    expect(DEFAULTS).toEqual({
      COUNTRY_ID: '101',
      COUNTRY_SORTNAME: 'IN',
      LIMIT: 5,
      PAGE: 1,
      TAX_GROUP: 'all',
    });

    expect(FILE_PATHS).toEqual({
      JSON_COUNTRIES: 'countries.json',
      JSON_CURRENCY: 'currency.json',
      JSON_TIMEZONE: 'timezone.json',
      JSON_GST_STATE: 'gst_state_code.json',
      STATE_PREFIX: 'state_',
    });
  });

  test('exports message maps', () => {
    expect(ERROR_MESSAGES).toMatchObject({
      NOT_FOUND: 'Setting not found',
      INVALID_DATA: 'Data Not Valid',
      UNAUTHORIZED: 'Unauthorized',
      UPDATE_FAILED: 'Failed to update setting',
      DELETE_FAILED: 'Failed to delete setting',
      TAX_NOT_FOUND: 'Tax not found',
      TAX_ADD_FAILED: 'Failed to add tax',
      TAX_UPDATE_FAILED: 'Failed to update tax',
      TAX_DELETE_FAILED: 'Failed to delete tax',
      TAX_GROUP_NOT_FOUND: 'Tax group not found',
      UNIT_NOT_FOUND: 'Unit not found',
      UNIT_ADD_FAILED: 'Failed to add unit',
      UNIT_UPDATE_FAILED: 'Failed to update unit',
      UNIT_DELETE_FAILED: 'Failed to delete unit',
      DENOM_NOT_FOUND: 'Denomination not found',
      DENOM_ADD_FAILED: 'Failed to add denomination',
      DENOM_UPDATE_FAILED: 'Failed to update denomination',
      DENOM_DELETE_FAILED: 'Failed to delete denomination',
      PAYMENT_NOT_FOUND: 'Payment method not found',
      PAYMENT_ADD_FAILED: 'Failed to add payment method',
      PAYMENT_UPDATE_FAILED: 'Failed to update payment method',
      PAYMENT_DELETE_FAILED: 'Failed to delete payment method',
      TABLE_ORDER_NOT_FOUND: 'Table order not found',
      TABLE_ORDER_ADD_FAILED: 'Failed to add table order',
      TABLE_ORDER_UPDATE_FAILED: 'Failed to update table order',
      TABLE_ORDER_DELETE_FAILED: 'Failed to delete table order',
      FILE_NOT_FOUND: 'File not found',
      FILE_UPLOAD_FAILED: 'File upload failed',
      INVALID_FILE_NAME: 'Invalid file name',
      IMAGE_DELETE_FAILED: 'Failed to delete image',
      PASSWORD_CHANGE_FAILED: 'Failed to change password',
      OLD_PASSWORD_INCORRECT: 'Old password is incorrect',
      COLLECTION_DELETE_FAILED: 'Failed to delete collection',
      CUSTOMER_SETTINGS_FAILED: 'Failed to update customer settings',
      SUPPLIER_SETTINGS_FAILED: 'Failed to update supplier settings',
      THEME_SETTINGS_FAILED: 'Failed to update theme settings',
      THEME_NOT_FOUND: 'No theme settings found',
      REQUIRED_FIELDS_MISSING: 'Required fields are missing',
      ID_REQUIRED: 'ID is required',
      INVALID_ID_FORMAT: 'Invalid ID format',
      SMS_SEND_FAILED: 'Failed to send SMS',
      BACKUP_FAILED: 'Backup operation failed',
      RESTORE_FAILED: 'Restore operation failed',
    });

    expect(SUCCESS_MESSAGES).toMatchObject({
      UPDATED: 'Setting updated successfully',
      DELETED: 'Setting deleted successfully',
      RETRIEVED: 'Setting retrieved successfully',
      TAX_ADDED: 'Tax added successfully',
      TAX_UPDATED: 'Tax updated successfully',
      TAX_DELETED: 'Tax deleted successfully',
      TAX_RETRIEVED: 'Tax retrieved successfully',
      TAX_GROUP_ADDED: 'Tax group added successfully',
      TAX_GROUP_UPDATED: 'Tax group updated successfully',
      TAX_GROUP_DELETED: 'Tax group deleted successfully',
      UNIT_ADDED: 'Unit added successfully',
      UNIT_UPDATED: 'Unit updated successfully',
      UNIT_DELETED: 'Unit deleted successfully',
      UNIT_RETRIEVED: 'Unit retrieved successfully',
      DENOM_ADDED: 'Denomination added successfully',
      DENOM_UPDATED: 'Denomination updated successfully',
      DENOM_DELETED: 'Denomination deleted successfully',
      DENOM_RETRIEVED: 'Denomination retrieved successfully',
      PAYMENT_ADDED: 'Payment method added successfully',
      PAYMENT_UPDATED: 'Payment method updated successfully',
      PAYMENT_DELETED: 'Payment method deleted successfully',
      PAYMENT_RETRIEVED: 'Payment methods retrieved successfully',
      TABLE_ORDER_ADDED: 'Table order added successfully',
      TABLE_ORDER_UPDATED: 'Table order updated successfully',
      TABLE_ORDER_DELETED: 'Table order deleted successfully',
      TABLE_ORDER_RETRIEVED: 'Table orders retrieved successfully',
      GENERAL_SETTING_UPDATED: 'General Setting updated',
      COMMON_SETTINGS_UPDATED: 'Common settings updated successfully',
      OFFLINE_SETTING_UPDATED: 'Offline setting updated successfully',
      SMS_SETTING_UPDATED: 'SMS setting updated successfully',
      LOGO_UPDATED: 'Branch logo updated successfully',
      KIOSK_IMAGES_UPDATED: 'Kiosk images updated successfully',
      IMAGE_STORED: 'Image data stored successfully',
      IMAGE_DELETED: 'Image deleted successfully',
      PASSWORD_CHANGED: 'Password changed successfully',
      CUSTOMER_SETTINGS_UPDATED: 'Customer settings updated successfully',
      SUPPLIER_SETTINGS_UPDATED: 'Supplier settings updated successfully',
      THEME_SETTINGS_UPDATED: 'Theme settings updated',
      THEME_SETTINGS_RETRIEVED: 'Theme settings retrieved successfully',
      COLLECTION_DELETED: 'Collection deleted successfully',
      PAYMENT_KEY_UPDATED: 'Payment key updated successfully',
      SMS_RECEIPT_SENT: 'SMS receipt sent successfully',
      BACKUP_CREATED: 'Backup created successfully',
      RESTORE_COMPLETED: 'Restore completed successfully',
    });
  });

  test('exports validation and collection structures', () => {
    expect(VALIDATION_RULES).toMatchObject({
      STORE_NAME: { MIN: 3, MAX: 250 },
      STORE_EMAIL: { MAX: 50 },
      STORE_TELEPHONE: { MIN: 3, MAX: 20 },
      STORE_ADDRESS: { MIN: 3, MAX: 500 },
      PRINTING_ADDRESS: { MIN: 3, MAX: 500 },
      WEBSITE: { MIN: 3, MAX: 50 },
      CITY: { MAX: 50 },
      PINCODE: { MAX: 15 },
      TAX_NAME: { MIN: 3, MAX: 20 },
      TAX_VALUE: { MIN: 1, MAX: 5 },
      UNIT_NAME: { MIN: 1, MAX: 20 },
      UNIT_VALUE: { MIN: 1, MAX: 6 },
      DENOM_VALUE: { MIN: 1, MAX: 5 },
      PAYMENT_VALUE: { MIN: 1, MAX: 12 },
      DEFAULT_CUSTOMER: { MIN: 3, MAX: 100 },
      DEFAULT_SUPPLIER: { MIN: 3, MAX: 100 },
      PASSWORD: { MIN: 5, MAX: 20 },
      WAY2SMS_API: { MAX: 100 },
      WAY2SMS_USERID: { MAX: 20 },
      TEXTLOCAL_API: { MAX: 100 },
      TEXTLOCAL_SENDER: { MAX: 20 },
    });

    expect(COLLECTIONS).toEqual({
      BRANCHES: 'branches',
      TAX: 'grouptax',
      UNIT: 'unit',
      DENOMINATION: 'denomination',
      TABLE_ORDER: 'tableorder',
      PAYMENT: 'payment_method',
      RECYCLE_BIN: 'recycle_bin',
    });
  });
});
